# DL Rankings

## Packages Needed
```{r}
#| message: false
library(tidyverse)
library(DT)
```

## Load DL Players
```{r}
dls <- read.csv("data/players.csv") %>% 
  filter(position == "DI")
```

## Load Necessary CSV Files
```{r}
defense <- read.csv("data/defense_summary.csv") %>% 
  select(player_id, missed_tackle_rate, grades_pass_rush_defense, grades_run_defense) # miss %, prsh_grade, rdef_grade
prsh_defense <- read.csv("data/pass_rush_summary.csv") %>% 
  select(player_id, pass_rush_win_rate, prp) # prsh_win_p, prp
run_defense <- read.csv("data/run_defense_summary.csv") %>% 
  select(player_id, stop_percent) # run_stop_p
```

## Combine Datasets
```{r}
dl_values <- dls %>% 
  left_join(defense, by = c("id" = "player_id")) %>% 
  drop_na()
dl_values <- dl_values %>% 
  left_join(prsh_defense, by = c("id" = "player_id")) %>% 
  drop_na()
dl_values <- dl_values %>% 
  left_join(run_defense, by = c("id" = "player_id")) %>% 
  drop_na()
dl_values <- dl_values %>% 
  rename(miss_p = missed_tackle_rate, rdef_grade = grades_run_defense, prsh_grade = grades_pass_rush_defense, prsh_win_p = pass_rush_win_rate, run_stop_p = stop_percent) %>%
  select(-id)
```

## Get Mean Values (for testing)
```{r}
mean(dl_values$miss_p)
mean(dl_values$rdef_grade)
mean(dl_values$prsh_grade)
mean(dl_values$prsh_win_p)
mean(dl_values$prp)
mean(dl_values$run_stop_p)
```

## Create Rating Function
```{r}
get_dl_ratings <- function(input_df) {
  df_dl_copy <- input_df %>% mutate(
    prsh_grade = round(pmax(pmin((prsh_grade-60) / 2, 10), 0), 2),  # 60-80, mean 70
    rdef_grade = round(pmax(pmin((rdef_grade-60) / 3, 10), 0), 2), # 60-90, mean 75
    prsh_win_p = round(pmax(pmin((prsh_win_p-4)*1.25, 10), 0), 2), # 4-12, mean 8
    run_stop_p = round(pmax(pmin((run_stop_p-4)*1.67, 10), 0), 2), # 4-10, mean 7
    prp = round(pmax(pmin((prp-2), 5), 0), 2), # 2-7, mean 4.5, worth 5
    miss_p = round(pmax(pmin(((100-miss_p)-82) / 1.8, 5), 0), 2), # 18-9, mean 13.5, worth 5
  )
  
  return(df_dl_copy)
}
```

## Create Final Dataset
```{r}
dl_ratings <- get_dl_ratings(dl_values) %>% 
  mutate(total = rowSums(select(.,-name, -position, -team, -rank))) %>% 
  arrange(-total) %>%
  mutate(pos_rank_aft = row_number())
```

## Display Ratings
```{r}
DT::datatable(
  dl_ratings,
  options = list(
    scrollX = TRUE,
    autoWidth = TRUE
  ),
  class = "compact stripe hover",
  fillContainer = FALSE
)
```
